wandb_version: 1

data_dir:
  desc: null
  value: pdbbind_output_mdb/split/data
mode:
  desc: null
  value: test
output_dir:
  desc: null
  value: output_train/rep_2
unobserved:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.0001
conv_drop_rate:
  desc: null
  value: 0.1
fc_drop_rate:
  desc: null
  value: 0.25
num_epochs:
  desc: null
  value: 300
num_conv:
  desc: null
  value: 4
batch_norm:
  desc: null
  value: false
no_dropout:
  desc: null
  value: false
batch_size:
  desc: null
  value: 16
random_seed:
  desc: null
  value: 9845977
_wandb:
  desc: null
  value:
    python_version: 3.9.20
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1729714168.084088
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.20
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
